//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Econocom.Model.Models.Benchmark;
using Econocom.Model.Models.CMS;
using Econocom.Model.Models.Traduction;

namespace Econocom.Model.Models.Traduction
{
    using System;
    using System.Collections.Generic;

    public partial class DeviseTraduction : Entity
    {
        public DeviseTraduction()
        {
            
        }

        public int DeviseId { get; set; }
        public int LangueId { get; set; }
        public string Libelle { get; set; }
        public System.DateTime DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }

        public virtual Devise Devise { get; set; }
        public virtual Langue Langue { get; set; }
    
       
    }
}
