//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Econocom.Model.Models.Benchmark;
using Econocom.Model.Models.CMS;

namespace Econocom.Model.Models.Traduction
{
    using System;
    using System.Collections.Generic;

    public partial class TarifTraduction : Entity
    {
        public int TarifId { get; set; }
        public int LangueId { get; set; }
        public string LibelleTarif { get; set; }        
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }

        public virtual Tarif Tarif { get; set; }
        public virtual Langue Langue { get; set; }
    }
}
