//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityReference
    {
        public long id { get; set; }
        public long segment_id { get; set; }
        public long type_id { get; set; }
        public long activity_id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivitySegment ActivitySegment { get; set; }
        public virtual ActivityType ActivityType { get; set; }
    }
}
