//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string siret { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<int> activity_segment_id { get; set; }
        public Nullable<int> activity_type_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> company_detail_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
