// <auto-generated />
namespace Econocom.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _02122013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02122013));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021301202_02122013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
