//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace Econocom.Model.ViewModel
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 
    /// </summary>
    public partial class CorrespondancePuissanceViewModel : EntityViewModel
    {
        public int TypeSocieteId { get; set; }
        public int TypeDeviceId { get; set; }
        public decimal Puissance1 { get; set; }
        public decimal Puissance2 { get; set; }
        public decimal Puissance3 { get; set; }

        public int Puissance1ClasseDeviceId { get; set; }
        public int Puissance2ClasseDeviceId { get; set; }
        public int Puissance3ClasseDeviceId { get; set; }
        
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
    }
}
