//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.Models.Benchmark
{
    using System;
    using System.Collections.Generic;

    public class DetailsClientViewModel : Entity
    {      
        public decimal TauxEquipement { get; set; }
        public int ChiffreAffaire { get; set; }
        public int NombreSite { get; set; }
        public decimal PrixKWH { get; set; }
        public int SuperficieDataCenter { get; set; }
        public int SuperficieTotale { get; set; }
        public string CodeInterneClient { get; set; }
        public int TarifId { get; set; }
        public int Effectif { get; set; }            
    }
}
