//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace Econocom.Model.ViewModel
{
    using System;
    using System.Collections.Generic;

    public partial class DeviseViewModel : EntityViewModel
    {
        public string Libelle { get; set; }
        public string CodeDevise { get; set; }
        public string UrlImage { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
        public HttpPostedFileBase File { get; set; }
    }
}
