//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.ViewModel
{
    using System;
    using System.Collections.Generic;

    public partial class OrigineViewModel : EntityViewModel
    {       
    
        //public int OrigineId { get; set; }
        public string LibelleOrigine { get; set; }
        public System.DateTime DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
           
    }
}
