//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.ViewModel
{
    using System;
    using System.Collections.Generic;

    public partial class TarifViewModel : EntityViewModel
    {
        //public int TarifId { get; set; }
        public string LibelleTarif { get; set; }
        public int NbreMinDevice { get; set; }
        public Nullable<int> NbreMaxDevice { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<int> TarifAnnuel { get; set; }
    }
}
