//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Econocom.Model.ViewModel;

namespace Econocom.Model.Models.Benchmark
{
    using System;
    using System.Collections.Generic;

    public partial class TypeObjetViewModel : EntityViewModel
    {
        //public int TypeObjetId { get; set; }
       
        public string NomTable { get; set; }
        public string NomObjet { get; set; }
        public string Namespace { get; set; }       
    }
}
