ALTER TABLE [dbo].[sysdiagrams]
    ADD CONSTRAINT [PK_sysdiagrams] PRIMARY KEY CLUSTERED ([diagram_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

