//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.Models.CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenuModere:Entity
    {
        //public int IdContenuModere { get; set; }
        public string Contenu { get; set; }        
        public Nullable<int> PageId { get; set; }
        public Nullable<int> CleModeleId { get; set; }
        public Nullable<int> LangueId { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }

        public virtual CleModele CleModele { get; set; }
        public virtual Langue Langue { get; set; }
        public virtual Page Page { get; set; }
    }
}
