//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Econocom.Model.Models.Benchmark;

namespace Econocom.Model.Models.CMS
{
    using System;
    using System.Collections.Generic;

    public partial class Langue : Entity
    {
        public Langue()
        {
            this.ContenuModeres = new HashSet<ContenuModere>();
            //this.ContenuNonModeres = new HashSet<ContenuNonModere>();
            //this.HistoriqueContenus = new HashSet<HistoriqueContenu>();
            this.Routages = new HashSet<Routage>();
        }

        //public int IdLangue { get; set; }
        public string Code { get; set; }
        public string Nom { get; set; }
        public string Culture { get; set; }
        public bool Defaut { get; set; }        
        public int PaysId { get; set; }
        public bool Localise { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
        public string LienImage { get; set; }
    
        public virtual ICollection<ContenuModere> ContenuModeres { get; set; }
        //public virtual ICollection<ContenuNonModere> ContenuNonModeres { get; set; }
        //public virtual ICollection<HistoriqueContenu> HistoriqueContenus { get; set; }
        public virtual ICollection<Routage> Routages { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
