//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.Models.CMS
{
    using System;
    using System.Collections.Generic;

    public partial class Modele : Entity
    {
        public Modele()
        {
            this.CleModeles = new HashSet<CleModele>();
            //this.HistoriqueModelePages = new HashSet<HistoriqueModelePage>();
            this.Pages = new HashSet<Page>();           
        }
    
        //public int ModeleId { get; set; }
        public string Nom { get; set; }
        public string Lien { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
    
        public virtual ICollection<CleModele> CleModeles { get; set; }
        //public virtual ICollection<HistoriqueModelePage> HistoriqueModelePages { get; set; }
        public virtual ICollection<Page> Pages { get; set; }        
    }
}
