//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.Models.CMS
{
    using System;
    using System.Collections.Generic;

    public partial class Section : Entity
    {
        public Section()
        {
            this.Pages = new HashSet<Page>();
            this.Sections = new HashSet<Section>();
        }
    
        //public int SectionId { get; set; }
        public string Nom { get; set; }
        public Nullable<int> ParentId { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual Section Parent { get; set; }
    }
}
