//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Econocom.Model;

namespace Econocom.Model.ViewModel.CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleModeleViewModel:EntityViewModel
    {       
        //public int CleModeleId { get; set; }
        public string Nom { get; set; }
        public Nullable<int> ModeleId { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }    
    }
}
