//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econocom.Model.ViewModel.CMS
{
    using System;
    using System.Collections.Generic;

    public partial class LangueViewModel : EntityViewModel
    {        
        public string Code { get; set; }
        public string Nom { get; set; }
        public string Culture { get; set; }
        public bool Defaut { get; set; }
        public string Pays { get; set; }
        public bool Localise { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public DateTime? DateModification { get; set; }
        public string LienImage { get; set; }    
    }
}
